# Generated by Django 2.2.3 on 2019-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0003_blog_events_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='title',
            field=models.CharField(default='dsfs', max_length=200),
            preserve_default=False,
        ),
    ]
