# Generated by Django 2.2.3 on 2019-08-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0004_songs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='cover_art'),
        ),
    ]
