# Generated by Django 2.2.3 on 2019-08-17 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0007_auto_20190817_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
