# Generated by Django 2.2.3 on 2019-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0008_songs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about_me',
            field=models.TextField(blank=True, help_text='Describe yourself in 300 words or less', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
