# Generated by Django 2.2.3 on 2019-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0009_auto_20190817_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
