# Generated by Django 2.2.3 on 2019-08-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0015_blog_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='edited_by',
        ),
    ]
