# Generated by Django 2.2.3 on 2019-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0016_remove_blog_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
