# Generated by Django 2.2.3 on 2019-08-17 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0018_blog_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
