# Generated by Django 2.2.4 on 2019-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fano_backend', '0019_videogallery_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='blog_song'),
        ),
    ]
